[general]
  # selection = [ ]
  # tag = "v0_23_0_"
  # Comment subtags for default compiler runs only
  subtags = [
    {intel_ = []},
    {gnu_ = ["deode/data/config_files/modifications/submission/atos_bologna_gnu.toml"]},
  ]

[include]
  cases = "case_definitions.toml"
  macros = "macros.toml"
  modifs = "modifs_atos_bologna.toml"
