[general]
  selection = [
    "cy49t2_alaro",
    "cy49t2_alaro_target",
    "cy49t2_arome_dp",
    "cy49t2_arome_target",
    "cy49t2_harmonie_arome_dp",
    "cy49t2_harmonie_arome_target",
  ]

[include]
  cases = "case_definitions.toml"
  macros = "macros.toml"
  modifs = "modifs_lumi.toml"
