[general]
  selection = [
    "cy49t2_arome_large_domain_operational",
    "cy49t2_harmonie_arome_operational",
  ]
  extra = ["deode/data/config_files/modifications/operational_settings_lumi.toml"]

[include]
  cases = "case_definitions.toml"
  macros = "macros.toml"
  modifs = "modifs_lumi_operational.toml"
